#' Remove scale() Transforms and Optionally Normalize Font Sizes in SVG Text Elements
#'
#' Parses an SVG file and removes any \code{scale()} transform applied to \code{<text>}
#' and \code{<tspan>} elements, and optionally sets a uniform font size across all
#' text nodes. This is useful as a post-processing step for SVG files generated by
#' \code{svglite}, which may add \code{scale()} transforms to text nodes as a kerning
#' correction. These transforms cause text to appear squished when editing font sizes
#' in vector graphics editors such as Inkscape or Illustrator.
#'
#' @param svg_file Character. Path to the SVG file to be processed. The file is
#'   modified in place.
#' @param font_size Numeric or \code{NULL}. If provided, sets all text elements to
#'   this font size in points (pt). If \code{NULL} (default), font sizes are left
#'   unchanged and only \code{scale()} transforms are removed.
#'
#' @details
#' When \code{svglite} renders text, it occasionally applies a \code{scale(x, 1)}
#' transform to text elements to correct letter spacing. While this produces
#' visually accurate output, it interferes with font size editing in vector
#' graphics editors: changing the font size rescales the text in only one
#' dimension, causing distortion.
#'
#' This function removes all \code{scale()} components from \code{transform}
#' attributes on \code{<text>} and \code{<tspan>} nodes. If the \code{transform}
#' attribute consists solely of a \code{scale()} call, the attribute is removed
#' entirely. Other transform functions (e.g. \code{translate()}, \code{rotate()})
#' are preserved.
#'
#' If \code{font_size} is specified, the function updates the \code{font-size}
#' property in the \code{style} attribute of each text node, and also sets the
#' \code{font-size} attribute directly if present. This allows batch-normalizing
#' font sizes across an entire figure after layout adjustments in Inkscape.
#'
#' Note: if you are using \code{svglite >= 2.0.0}, consider setting
#' \code{fix_text_size = FALSE} in \code{\link[svglite]{svglite}} instead, which
#' prevents \code{textLength} constraints from being written in the first place
#' and is the preferred solution. This function is intended for post-processing
#' of existing SVG files where regeneration is not possible.
#'
#' @return Invisibly returns \code{svg_file} (the input path). The file is
#'   overwritten in place.
#'
#' @seealso \code{\link{export_plot_dual}} for generating publication-ready SVG
#'   files with \code{fix_text_size = FALSE}.
#'
#' @examples
#' \dontrun{
#' # Only remove scale() transforms, keep original font sizes
#' normalize_svg_text("figures/my_umap.svg")
#'
#' # Remove scale() transforms and set all text to 8pt
#' normalize_svg_text("figures/my_umap.svg", font_size = 8)
#'
#' # Use in combination with export_plot_dual()
#' export_plot_dual("figures/my_plot", my_ggplot)
#' normalize_svg_text("figures/my_plot.svg", font_size = 8)
#' }
#'
#' @importFrom xml2 read_xml xml_find_all xml_attr xml_set_attr write_xml
#' @export
normalize_svg_text <- function(svg_file, font_size = NULL) {
  
  if (!requireNamespace("xml2", quietly = TRUE)) {
    stop("Package 'xml2' is required. Please install it with: install.packages('xml2')")
  }
  
  if (!is.null(font_size) && (!is.numeric(font_size) || length(font_size) != 1 || font_size <= 0)) {
    stop("'font_size' must be a single positive numeric value or NULL.")
  }
  
  svg <- xml2::read_xml(svg_file)
  
  text_nodes  <- xml2::xml_find_all(svg, "//*[local-name()='text']")
  tspan_nodes <- xml2::xml_find_all(svg, "//*[local-name()='tspan']")
  all_nodes   <- c(text_nodes, tspan_nodes)
  
  for (node in all_nodes) {
    
    # --- Remove scale() transforms ---
    transform <- xml2::xml_attr(node, "transform")
    if (!is.na(transform)) {
      # Remove any scale() call regardless of its arguments:
      # - scale(x, 1): x-only kerning correction added by svglite
      # - scale(1, y): would squish text vertically
      # - scale(x, y): would distort in both dimensions
      # Other transform functions (translate, rotate, etc.) are preserved.
      cleaned <- gsub("scale\\([^)]+\\)", "", transform)
      cleaned <- trimws(cleaned)
      
      if (nchar(cleaned) == 0) {
        xml2::xml_set_attr(node, "transform", NULL)
      } else {
        xml2::xml_set_attr(node, "transform", cleaned)
      }
    }
    
    # --- Optionally normalize font size ---
    if (!is.null(font_size)) {
      
      # Update font-size inside style attribute (e.g. "font-size:12px;fill:#000")
      style <- xml2::xml_attr(node, "style")
      if (!is.na(style)) {
        style <- gsub("font-size:\\s*[0-9.]+\\s*(?:px|pt|em|rem|%)?",
                      paste0("font-size:", font_size, "pt"),
                      style, perl = TRUE)
        xml2::xml_set_attr(node, "style", style)
      }
      
      # Update standalone font-size attribute if present
      if (!is.na(xml2::xml_attr(node, "font-size"))) {
        xml2::xml_set_attr(node, "font-size", paste0(font_size, "pt"))
      }
    }
  }
  
  xml2::write_xml(svg, svg_file)
  
  if (is.null(font_size)) {
    message("Removed scale() transforms from: ", svg_file)
  } else {
    message("Removed scale() transforms and set font size to ", font_size, "pt in: ", svg_file)
  }
  
  invisible(svg_file)
}